
- name: Create Dev Server
  hosts: devcontainer
  become: true
  tasks:
  - name: Add podman PPA
  ansible.builtin.apt_repository:
    repo: 'ppa:projectatomic/ppa'
  - name: Install podman suite of tools
    ansible.builtin.package:
      name: "{{ item }}"
      update_cache: yes
    with_items:
    - podman
    - podman-docker
    - podman-gvproxy
    - podman-netavark
    - python3-podman-compose
    - uidmap
    - containernetworking-podman-machine
    - containernetworking-plugins
    - containernetworking-dnsname

