
- name: Create Dev Server
  hosts: devcontainer
  become: true
  roles:
    - geerlingguy.docker
  tasks:
    - name: Add marksie1988 to docker group
      ansible.builtin.user:
        groups: docker
        append: true
