
- name: Create Dev Server
  hosts: devcontainer
  become: true
  tasks:
  - name: Install podman suite of tools
    ansible.builtin.package:
      name: "{{ items }}"
      update_cache: yes
    with_items:
    - podman
    - podman-docker
    - podman-gvproxy
    - podman-netavark
    - python3-podman-compose
    - uidmap
    - containernetworking-podman-machine
    - containernetworking-plugins
    - containernetworking-dnsname

