---

- name: Create Docker Host
  hosts: docker
  become: true
  roles:
    - role: docker
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - nfs-common
          - python3-pip
        state: present

    - name: Install required python packages
      ansible.builtin.pip:
        name:
          - jsondiff
          - docker
    - name: Copy portainer compose file
      ansible.builtin.copy:
        src: portainer-stack.yml
        dest: /opt/portainer-stack.yml
    - name: Deploy portainer stack
      community.docker.docker_stack:
        state: present
        name: portainer
        compose:
          - /opt/portainer-stack.yml
