---

- hosts: hassio
  roles:
    - role: docker
      become: true
    - role: hassio
      become: true
    # - webhook

  tasks:
    - name: Pause until a Hassio is reachable from this host
      uri:
        url: "http://127.0.0.1:8123/"
        method: GET
        follow_redirects: all
        return_content: true
      register: _result
      until:
        - _result.status == 200
        - _result.content.find('Preparing') == -1
      retries: 180 # 180 * 5 seconds = 15mins (60*60/5)
      delay: 5 # Every 5 seconds
      become: true

    - name: Add custom Addon repos
      totaldebug.hassio_cli.hassio_addon_repos:
        state: present
        repo: "https://github.com/helto4real/hassio-add-ons"
      become: true

    # Installs HASSIO Addons using https://github.com/totaldebug/ansible-module-hassio
    - name: Install Addons
      totaldebug.hassio_cli.hassio_addons:
        state: present
        name: "{{ item }}"
      with_items:
        - a0d7b954_grafana
        - core_mosquitto
        - core_deconz
      become: true
