---

- hosts: hassio
  roles:
    - base
    - ansible-motd
    - ansible-role-docker
    - ansible-hassio
---

- hosts: hassio
  become: yes
  roles: 
    - motd
    - docker
    - hassio
    - webhook
