---

- hosts: hassio
  roles:
    - motd
    - role: docker
      become: true
    - role: hassio
      become: true
    # - webhook

  tasks:
    - hassio_addons:
        state: present
        name: "{{ item }}"
      with_items:
        - grafana
        - core_mosquitto
        - core_deconz
