- name: Configure all servers.
  hosts: all
  become: true
  become_method: sudo
  roles:
  - base
  - geerlingguy.security
  - totaldebug.motd
  - totaldebug.users

- import_playbook: bastion.yml

- import_playbook: backups.yml
  #- import_playbook: hassio.yml
- import_playbook: tor.yml

- import_playbook: minecraft.yml

- import_playbook: proxy.yml

- import_playbook: plex.yml
  #- import_playbook: docker.yml
- import_playbook: devcontainer.yml

- import_playbook: docker.yml

- import_playbook: unifi.yaml
