---
- name: Configure all servers.
  hosts: all
  become: true
  roles:
    - base
    - security
    - totaldebug.users

- import_playbook: hassio.yml

- import_playbook: tor.yml

- import_playbook: minecraft.yml

- import_playbook: proxy.yml

- import_playbook: plex.yml
