- hosts: proxy
  roles:
    - role: totaldebug.webhook
    - role: totaldebug.certbot
      become: true
  tasks:
    - name: Copy Git SSH Key
      ansible.builtin.copy:
        content: "{{ lookup('community.general.onepassword', 'proxy_git_key', fields=priv_key) }}"
        dest: /root/.ssh/github
        group: root
        owner: root
        mode: 0600
      become: true
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
      become: true
    - name: Deleting default nginx config
      ansible.builtin.file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      become: true
    - name: Checkout nginx config
      ansible.builtin.git:
        repo: git@github.com:marksie1988/reverse-proxy.git
        dest: /etc/nginx/conf.d/
        force: true
        accept_hostkey: true
        key_file: /root/.ssh/github
      become: true
    - name: Change permission on deploy-hook.sh file
      ansible.builtin.file:
        path: /etc/nginx/conf.d/deploy-hook.sh
        state: file
        mode: 0755
      become: true
    - name: Start Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: true
      become: true
