- hosts: proxy
  roles:
    - role: totaldebug.webhook
    - role: totaldebug.certbot
      become: true
  tasks:
    - name: Checkout nginx config
      ansible.builtin.git:
        repo: git@github.com:marksie1988/reverse-proxy.git
        dest: /etc/nginx/conf.d/
        accept_hostkey: true
    - name: Change permission on deploy-hook.sh file
      file:
        path: /etc/nginx/conf.d/deploy-hook.sh
        state: file
        mode: 0755
