- hosts: proxy
  roles:
    - role: totaldebug.webhook
    - role: totaldebug.certbot
      become: true
  tasks:
    - name: Add user to nginx group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: www-data
        append: true
    - name: Checkout nginx config
      ansible.builtin.git:
        repo: git@github.com:marksie1988/reverse-proxy.git
        dest: ~/reverse-proxy
        accept_hostkey: true
    - name: Change permission on deploy-hook.sh file
      file:
        path: /etc/nginx/conf.d/deploy-hook.sh
        state: file
        mode: 0755
      become: true
