- hosts: proxy
  roles:
    - role: totaldebug.webhook
    - role: totaldebug.certbot
      become: true
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
      become: true
    - name: Checkout nginx config
      ansible.builtin.git:
        repo: git@github.com:marksie1988/reverse-proxy.git
        dest: /etc/nginx/sites-enabled/
        accept_hostkey: true
      become: true
    - name: Change permission on deploy-hook.sh file
      file:
        path: /etc/nginx/conf.d/deploy-hook.sh
        state: file
        mode: 0755
      become: true
    - name: Start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
