---
roles:
  - name: totaldebug.users
  - name: totaldebug.deluge
  - name: totaldebug.hassio
  - name: totaldebug.motd
  - name: totaldebug.webhook
  - name: totaldebug.certbot
  - name: totaldebug.minecraft
  - name: geerlingguy.security
    version: 2.2.0
  - name: geerlingguy.docker
    version: 6.0.1
  - name: totaldebug.minecraft
  - name: geerlingguy.nfs
    version: 2.0.0
  - name: githubixx.ansible_role_wireguard
    version: 10.0.0

collections:
  - name: community.general
  - name: totaldebug.hassio_cli
    version: 3.0.0
