---
- hosts: tor
  roles:
    - totaldebug.motd
    - totaldebug.deluge
    - role: geerlingguy.nfs
      become: true
    - role: githubixx.ansible_role_wireguard
      become: true
  tasks:
    - name: Enable Wireguard
      ansible.builtin.service:
        name: wg-quick@wg0
        enabled: true
        state: started
      become: true
    - name: add backports repository
      apt_repository:
        repo: deb http://deb.debian.org/debian buster-backports main
        state: present
        update_cache: true
      become: true
    - name: Install backports IPTables
      ansible.builtin.apt:
        name: iptables
        default_release: buster-backports
        state: present
      become: true
    - name: Install Firewalld & Python3-pip
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - firewalld
        - python3-pip
      become: true
    - name: Install dns python package
      pip:
        name: dnspython
      become: true
    - name: Enable Firewalld
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started
      become: true
    - name: Set public zone interface
      ansible.posix.firewalld:
        zone: public
        interface: eth0
        permanent: true
        state: enabled
      become: true
    - name: Update public firewall rule
      ansible.posix.firewalld:
        zone: public
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - 62952/tcp
        - 62952/udp
      become: true
    - name: Add zone work and source
      ansible.posix.firewalld:
        zone: work
        source: 1.1.1.1
        permanent: true
        state: enabled
      become: true
    - name: Update work firewall rule
      ansible.posix.firewalld:
        zone: work
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - 8112/tcp
        - 2812/tcp
        - 10050/tcp
        - 9117/tcp
      become: true
    - name: Add SSH to work
      ansible.posix.firewalld:
        zone: work
        service: ssh
        permanent: true
        state: enabled
      become: true
    - name: copy firewall update script
      ansible.builtin.template:
        src: firewall_update.py.j2
        dest: /usr/local/bin/firewall_update.py
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
      become: true
    - name: create cron to update firewall
      ansible.builtin.cron:
        name: "check firewall"
        minute: "*/5"
        job: "/bin/python3 /usr/local/bin/firewall_update.py"
        user: root
      become: true
    - name: Reboot server
      ansible.builtin.reboot:
      become: true
