---
- hosts: tor
  roles:
    - totaldebug.motd
    - totaldebug.deluge
    - role: geerlingguy.nfs
      become: true
    - role: githubixx.ansible_role_wireguard
      become: true
  tasks:
    - name: Install Firewalld 
      ansible.builtin.package:
        name: firewalld
        state: present
      become: true
    - name: Enable Firewalld
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started
      become: true
    - name: Update public firewall rule
      ansible.posix.firewalld:
        zone: public
        port: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
        - 62952/tcp
        - 62952/udp
      become: true
    - name: Update remote access firewall rule
      ansible.posix.firewalld:
        zone: remote_access
        source: 1.1.1.1
        port: "{{ item }}"
        service: ssh
        permanent: yes
        state: enabled
      with_items:
        - 8112/tcp
        - 2812/tcp
        - 10050/tcp
        - 9117/tcp
      become: true
    - name: copy firewall update script
      ansible.builtin.template:
        src: firewall_update.py.j2
        dest: /usr/local/bin/firewall_update.py
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
      become: true
    - name: create cron to update firewall
      ansible.builtin.cron:
        name: "check firewall"
        minute: "*/5"
        job: "/bin/python3 /usr/local/bin/firewall_update.py"
        user: root
      become: true
