---
- hosts: tor
  tasks:
    - name: sho priv key
      debug:
        var: "{{ wireguard_private_key }}"
  roles:
    - totaldebug.motd
    - totaldebug.deluge
    - role: geerlingguy.nfs
      become: true
    - role: githubixx.ansible_role_wireguard
      become: true
