- hosts: unifi
  tasks:
  - name: Install required packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    with_items:
    - ca-certificates
    - apt-transport-https
    become: true

  - name: Install
    command:
      cmd: curl -sO https://get.glennr.nl/unifi/install/install_latest/unifi-latest.sh && bash unifi-latest.sh --skip --add-repository
    become: true
