- hosts: unifi
  tasks:
  - name: add backports repository
    apt_repository:
      repo: deb http://deb.debian.org/debian buster-backports main
      state: present
      update_cache: true
    become: true
  - name: Install required packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    with_items:
    - ca-certificates
    - apt-transport-https
    become: true

  - name: Add source list
    command:
      cmd: echo 'deb [ arch=amd64,arm64 ] https://www.ui.com/downloads/unifi/debian stable ubiquiti' | sudo tee /etc/apt/sources.list.d/100-ubnt-unifi.list
    become: true

  - name: Add gpg key
    ansible.builtin.apt_key:
      keyserver: keyserver.ubuntu.com
      id: 06E85760C0A52C50

  - name: Install unifi
    ansible.builtin.package:
      name: unifi
      state: present
    become: true

  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: unifi
      state: started
      enabled: true
