---
- name: Initialize Docker Swarm
  command: docker swarm init --advertise-addr "{{ swarm_cluster_ip }}"
  register: swarm_init
  changed_when: false
  failed_when: "'already exists' not in swarm_init.stderr"

- name: Get Swarm Manager Token
  command: docker swarm join-token manager -q
  register: manager_token

- name: Get Swarm Worker Token
  command: docker swarm join-token worker -q
  register: worker_token

- name: Add Swarm Managers
  command: docker swarm join --token "{{ manager_token.stdout }}" "{{ swarm_init.stdout_lines[1] }}"
  when: inventory_hostname in groups['all'][0:number_of_managers]
  register: join_manager
  changed_when: false
  failed_when: "not join_manager.stdout"

- name: Add Swarm Workers
  command: docker swarm join --token "{{ worker_token.stdout }}" "{{ swarm_init.stdout_lines[1] }}"
  when: inventory_hostname not in groups['all'][0:number_of_managers]
  register: join_worker
  changed_when: false
  failed_when: "not join_worker.stdout"
