---
- name: Initialize Docker Swarm
  command: docker swarm init --advertise-addr "{{ swarm_cluster_ip }}"
  args:
    creates: /var/run/docker/swarm/control_token
  register: swarm_init_output
  tags: init_swarm
  when: swarm_init_output is not defined

- name: Retrieve Swarm join token
  command: docker swarm join-token -q worker
  changed_when: false
  register: join_token
  tags: get_join_token

- name: Add managers to Docker Swarm
  command: docker swarm join --token {{ join_token.stdout }} {{ swarm_init_output.stdout_lines[0] }}
  when: inventory_hostname == groups['swarm'][0]
  tags: join_managers

- name: Add workers to Docker Swarm
  command: docker swarm join --token {{ join_token.stdout }} {{ swarm_init_output.stdout_lines[0] }}
  when: inventory_hostname != groups['swarm'][0]
  tags: join_workers
