---
- name: Install nfs-common
  ansible.builtin.package:
    name: nfs-common
    state: present

- name: Install jsondiff python package
  ansible.builtin.pip:
    name: jsondiff

- name: Copy portainer compose file
  ansible.builtin.copy:
    src: portainer-stack.yml
    dest: /opt/portainer-stack.yml

- name: Deploy portainer stack
  community.docker.docker_stack:
    state: present
    name: portainer
    compose:
      - /opt/portainer-stack.yml
