---
version: "3.2"

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  portainer_data:
    driver_opts:
      type: "nfs"
      o: "addr=172.16.60.2,nfsvers=4"
      device: ":/export/dockerfiles/portainer/data"
