---
version: "3.2"

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - homepage.group=//Infrastructure
      - homepage.name=Portainer
      - homepage.icon=portainer.png
      - homepage.href=https://172.16.20.50:9443
      - homepage.description=Docker Container Manager
      - homepage.widget.type=portainer
      - homepage.widget.url=https://172.16.20.50:9443
      - homepage.widget.env=2
      - homepage.widget.key=ptr_JfbRS6oMqFfQZHkGjtnbDcc9GV/WK1lQjuLgoAHyPc4=

volumes:
  portainer_data:
    driver_opts:
      type: "nfs"
      o: "addr=172.16.60.2,nfsvers=4"
      device: ":/export/dockerfiles/portainer/data"
