---
- name: Wait for cloud-init to complete
  shell: /usr/bin/cloud-init status --wait
  register: cloud_init_install
  retries: 60
  delay: 5
  until: cloud_init_install is success

- name: install updates (CentOS)
  tags: always
  dnf:
    update_only: true
    update_cache: true
  become: true
  when: ansible_distribution == "CentOS"

- name: install updates (Ubuntu)
  tags: always
  apt:
    upgrade: dist
    update_cache: true
  become: true
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Install zsh, curl & unzip
  ansible.builtin.package:
    name:
      - zsh
      - curl
      - unzip
    state: present
