---

- name: install updates (CentOS)
  tags: always
  dnf:
    update_only: yes
    update_cache: yes
  become: true
  when: ansible_distribution == "CentOS"

- name: install updates (Ubuntu)
  tags: always
  apt:
    upgrade: dist
    update_cache: yes
  become: true
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
