---
- name: Wait for cloud-init to complete
  shell: journalctl --boot _COMM=cloud-init | grep 'Cloud-init.*finished at'
  register: cloud_init_install
  retries: 60
  delay: 5
  until: cloud_init_install is success

- name: install updates (CentOS)
  tags: always
  dnf:
    update_only: true
    update_cache: true
  become: true
  when: ansible_distribution == "CentOS"

- name: install updates (Ubuntu)
  tags: always
  apt:
    upgrade: dist
    update_cache: true
  become: true
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
